-- Migration: Create Timeline Feature Tables
-- Purpose: Foundation for recruiting timeline system with tasks, athlete progress, suggestions, and view logging
-- Version: 1.0

-- Create task table: Master list of recruiting timeline tasks
CREATE TABLE IF NOT EXISTS task (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category VARCHAR(20) NOT NULL CHECK (category IN ('academic', 'athletic', 'recruiting', 'exposure', 'mindset')),
  grade_level INTEGER NOT NULL CHECK (grade_level BETWEEN 9 AND 12),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  required BOOLEAN DEFAULT false,
  dependency_task_ids UUID[] DEFAULT ARRAY[]::UUID[],
  why_it_matters TEXT,
  failure_risk TEXT,
  division_applicability VARCHAR(10)[] DEFAULT ARRAY['ALL']::VARCHAR[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_task_grade_level ON task(grade_level);
CREATE INDEX IF NOT EXISTS idx_task_category ON task(category);
CREATE INDEX IF NOT EXISTS idx_task_grade_category ON task(grade_level, category);

-- Create athlete_task table: Track athlete's progress on tasks
CREATE TABLE IF NOT EXISTS athlete_task (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  task_id UUID NOT NULL REFERENCES task(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'completed', 'skipped')),
  completed_at TIMESTAMPTZ,
  is_recovery_task BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(athlete_id, task_id)
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_athlete_task_athlete ON athlete_task(athlete_id);
CREATE INDEX IF NOT EXISTS idx_athlete_task_status ON athlete_task(athlete_id, status);
CREATE INDEX IF NOT EXISTS idx_athlete_task_recovery ON athlete_task(athlete_id, is_recovery_task) WHERE is_recovery_task = true;
CREATE INDEX IF NOT EXISTS idx_athlete_task_completed ON athlete_task(athlete_id, completed_at DESC);

-- Create suggestion table: Store rule engine suggestions
CREATE TABLE IF NOT EXISTS suggestion (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rule_type VARCHAR(50) NOT NULL,
  urgency VARCHAR(10) NOT NULL CHECK (urgency IN ('low', 'medium', 'high')),
  message TEXT NOT NULL,
  action_type VARCHAR(50),
  related_school_id UUID REFERENCES schools(id) ON DELETE SET NULL,
  related_task_id UUID REFERENCES task(id) ON DELETE SET NULL,
  dismissed BOOLEAN DEFAULT false,
  dismissed_at TIMESTAMPTZ,
  completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  pending_surface BOOLEAN DEFAULT true,
  surfaced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for suggestion queries
CREATE INDEX IF NOT EXISTS idx_suggestion_athlete_surfaced ON suggestion(athlete_id, surfaced_at DESC);
CREATE INDEX IF NOT EXISTS idx_suggestion_pending ON suggestion(pending_surface, created_at ASC) WHERE pending_surface = true;
CREATE INDEX IF NOT EXISTS idx_suggestion_athlete_active ON suggestion(athlete_id, dismissed, completed) WHERE dismissed = false AND completed = false;
CREATE INDEX IF NOT EXISTS idx_suggestion_urgency ON suggestion(athlete_id, urgency) WHERE dismissed = false AND completed = false;

-- Create parent_view_log table: Track when parents view athlete data
CREATE TABLE IF NOT EXISTS parent_view_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  athlete_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  viewed_item_type VARCHAR(50) NOT NULL,
  viewed_item_id UUID,
  viewed_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT parent_must_be_parent CHECK (parent_user_id != athlete_id)
);

-- Create indexes for view log queries
CREATE INDEX IF NOT EXISTS idx_parent_view_athlete ON parent_view_log(athlete_id, viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_parent_view_parent ON parent_view_log(parent_user_id, viewed_at DESC);

-- Add comments for documentation
COMMENT ON TABLE task IS 'Master list of recruiting timeline tasks across all grades (9-12) and categories';
COMMENT ON TABLE athlete_task IS 'Track individual athlete progress on each task';
COMMENT ON TABLE suggestion IS 'Store suggestions generated by rule engine for surfacing to athletes';
COMMENT ON TABLE parent_view_log IS 'Track when parents view items for symmetric visibility';
