-- Issue #578: seed scholarship_limits from data/scholarshipLimits.json
-- (95 rows: 19 app sports x 5 divisions). See data/scholarshipLimits.README.md
-- for sourcing, the 2025-26 House v. NCAA roster-limit context, and the
-- documented sex/gender-representative-value limitation (schema has no
-- sex column, so rows with a men's/women's split pick one figure and note
-- the other). Idempotent — re-running updates existing rows to match the
-- seed file rather than erroring on the (sport, division) unique constraint.

insert into public.scholarship_limits (sport, division, total, head_count, equivalency, notes)
values
  ('Baseball', 'D1', 11.7, null, 11.7, 'Equivalency sport. 2025-26 roster limit: 34 (House v. NCAA settlement) — not a scholarship count.'),
  ('Baseball', 'D2', 9.0, null, 9.0, 'NCAA D2 equivalency limit, unaffected by the 2025 settlement.'),
  ('Baseball', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships — aid is need-based/academic only, any sport.'),
  ('Baseball', 'NAIA', 12, null, 12, 'Secondary-sourced (2aDays), not cross-confirmed against a primary NAIA document — verify.'),
  ('Baseball', 'JUCO', null, null, null, 'NJCAA publishes no numeric per-sport table; funding is by NJCAA division tier (D1 full-ride, D2 tuition/fees/books only, D3 none), not a fixed count.'),
  ('Softball', 'D1', 12, 12, null, 'Head-count sport. 2025-26 roster limit: 25.'),
  ('Softball', 'D2', 7.2, null, 7.2, 'NCAA D2 equivalency limit.'),
  ('Softball', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Softball', 'NAIA', 10, null, 10, 'Secondary-sourced, lower confidence — verify.'),
  ('Softball', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Basketball', 'D1', 15, 15, null, 'Head-count sport. This app doesn''t track athlete sex, so this uses the women''s D1 figure (15) — men''s D1 is 13. 2025-26 roster limit: 15 (both).'),
  ('Basketball', 'D2', 10.0, null, 10.0, 'NCAA D2 equivalency limit — men''s and women''s are both 10.0, no ambiguity here.'),
  ('Basketball', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Basketball', 'NAIA', 11, null, 11, 'Sources disagree (6-11 reported across sites for men''s/women''s) — low confidence, verify against a current NAIA compliance document.'),
  ('Basketball', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Football', 'D1', 85, 85, null, 'FBS head-count limit (85); FCS is equivalency, historically ~63 — schools.division has no FBS/FCS distinction. 2025-26 roster limit: 105 (both).'),
  ('Football', 'D2', 36, null, 36, 'NCAA D2 equivalency limit.'),
  ('Football', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Football', 'NAIA', 24, null, 24, 'Secondary-sourced, lower confidence — verify.'),
  ('Football', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Soccer', 'D1', 14, null, 14, 'This app doesn''t track athlete sex, so this uses the women''s D1 figure (14) — men''s D1 is 9.9. 2025-26 roster limit: 28 (both).'),
  ('Soccer', 'D2', 9.9, null, 9.9, 'Women''s D2 figure — men''s D2 is 9.0 (close).'),
  ('Soccer', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Soccer', 'NAIA', 12, null, 12, 'Secondary-sourced — men''s and women''s both reported around 12, no ambiguity here.'),
  ('Soccer', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Volleyball', 'D1', 12, 12, null, 'Women''s D1 head-count figure (volleyball is predominantly women''s-sponsored, ~24 D1 men''s programs vs. 300+ women''s). Men''s D1 is 4.5 equivalency. 2025-26 roster limit: 18 (both).'),
  ('Volleyball', 'D2', 8.0, null, 8.0, 'Women''s D2 figure — men''s D2 is 4.5 (far fewer programs).'),
  ('Volleyball', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Volleyball', 'NAIA', 8, null, 8, 'Secondary-sourced — men''s and women''s both reported at 8, no ambiguity here.'),
  ('Volleyball', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Track & Field', 'D1', 18, null, 18, 'This app doesn''t track athlete sex, so this uses the women''s D1 figure (18) — men''s D1 is 12.6. 2025-26 combined T&F+XC roster limit reported around 62 (both).'),
  ('Track & Field', 'D2', 12.6, null, 12.6, 'NCAA D2 equivalency limit, combined T&F/XC — men''s and women''s both 12.6, no ambiguity here.'),
  ('Track & Field', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Track & Field', 'NAIA', 12, null, 12, 'Secondary-sourced, lower confidence — verify.'),
  ('Track & Field', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Cross Country', 'D1', null, null, null, 'Typically shares the track & field scholarship pool, not a separate allotment. 2025-26 roster limit: 17 (both).'),
  ('Cross Country', 'D2', null, null, null, 'Typically shares the track & field D2 equivalency pool (12.6), not a separately reported figure.'),
  ('Cross Country', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Cross Country', 'NAIA', 5, null, 5, 'Secondary-sourced — men''s and women''s both reported at 5, no ambiguity here.'),
  ('Cross Country', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Swimming', 'D1', 14, null, 14, 'This app doesn''t track athlete sex, so this uses the women''s D1 figure (14, swimming & diving) — men''s D1 is 9.9. 2025-26 roster limit: 30 (both).'),
  ('Swimming', 'D2', 8.1, null, 8.1, 'NCAA D2 equivalency limit, swimming & diving — men''s and women''s both 8.1, no ambiguity here.'),
  ('Swimming', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Swimming', 'NAIA', 8, null, 8, 'Secondary-sourced — men''s and women''s both reported at 8, no ambiguity here.'),
  ('Swimming', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Golf', 'D1', 6, null, 6, 'This app doesn''t track athlete sex, so this uses the women''s D1 figure (6) — men''s D1 is 4.5. 2025-26 roster limit: 9 (both).'),
  ('Golf', 'D2', 5.4, null, 5.4, 'Women''s D2 figure — men''s D2 is 3.6.'),
  ('Golf', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Golf', 'NAIA', 5, null, 5, 'Sources vary 5-6 across genders — flagged, unverified.'),
  ('Golf', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Tennis', 'D1', 8, 8, null, 'Women''s D1 head-count figure — men''s D1 is 4.5 equivalency (different type, not just a different number). 2025-26 roster limit: 10 (both).'),
  ('Tennis', 'D2', 6.0, null, 6.0, 'Women''s D2 figure — men''s D2 is 4.5.'),
  ('Tennis', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Tennis', 'NAIA', 5, null, 5, 'Secondary-sourced — men''s and women''s both reported at 5, no ambiguity here.'),
  ('Tennis', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Wrestling', 'D1', 9.9, null, 9.9, 'Traditional men''s D1 figure (wrestling is overwhelmingly men''s-sponsored at NCAA D1 scale; women''s wrestling is a fast-growing separately-funded emerging sport with no established single figure yet). 2025-26 roster limit: 30.'),
  ('Wrestling', 'D2', 9.0, null, 9.0, 'NCAA D2 equivalency limit (men''s) — women''s D2 wrestling is 10.0 where sponsored.'),
  ('Wrestling', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Wrestling', 'NAIA', 8, null, 8, 'One source cites 10 instead of 8 — flagged, unverified.'),
  ('Wrestling', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Lacrosse', 'D1', 12, null, 12, 'Women''s D1 figure — men''s D1 is 12.6, nearly identical. 2025-26 roster limits: men''s 48 / women''s 38.'),
  ('Lacrosse', 'D2', 9.9, null, 9.9, 'Women''s D2 figure — men''s D2 is 10.8.'),
  ('Lacrosse', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Lacrosse', 'NAIA', 12, null, 12, 'Secondary-sourced — men''s and women''s both reported at 12, no ambiguity here.'),
  ('Lacrosse', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Ice Hockey', 'D1', 18, null, 18, 'Men''s and women''s D1 are both 18, no ambiguity here. 2025-26 roster limit: 26 (both).'),
  ('Ice Hockey', 'D2', 18.0, null, 18.0, 'Women''s D2 figure — men''s D2 is 13.5.'),
  ('Ice Hockey', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Ice Hockey', 'NAIA', null, null, null, 'Not found with confidence — ice hockey is rare at NAIA level, no reliable figure located.'),
  ('Ice Hockey', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Field Hockey', 'D1', 12, null, 12, 'Field hockey is women''s-sponsored in the US collegiate system. 2025-26 roster limit: 27.'),
  ('Field Hockey', 'D2', 6.3, null, 6.3, 'NCAA D2 equivalency limit.'),
  ('Field Hockey', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Field Hockey', 'NAIA', null, null, null, 'Not found with confidence — field hockey is rare at NAIA level, no reliable figure located.'),
  ('Field Hockey', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Rowing', 'D1', 20, null, 20, 'Rowing is predominantly women''s-sponsored for scholarship purposes (men''s rowing is mostly club/non-scholarship). 2025-26 roster limit: 68.'),
  ('Rowing', 'D2', 20.0, null, 20.0, 'NCAA D2 equivalency limit (women''s).'),
  ('Rowing', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Rowing', 'NAIA', null, null, null, 'Not found with confidence — rowing is rare at NAIA level, no reliable figure located.'),
  ('Rowing', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Water Polo', 'D1', 8, null, 8, 'This app doesn''t track athlete sex, so this uses the women''s D1 figure (8) — men''s D1 is 4.5. 2025-26 roster limit: 24 (both).'),
  ('Water Polo', 'D2', 8.0, null, 8.0, 'Women''s D2 figure — men''s D2 is 4.5.'),
  ('Water Polo', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Water Polo', 'NAIA', null, null, null, 'Not found with confidence — water polo is rare at NAIA level, no reliable figure located.'),
  ('Water Polo', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Gymnastics', 'D1', 12, 12, null, 'Women''s D1 head-count figure (men''s gymnastics is nearly extinct at D1, ~12 programs nationally). Men''s D1 is 6.3 equivalency. 2025-26 roster limit: 20 (both).'),
  ('Gymnastics', 'D2', 6.0, null, 6.0, 'Women''s D2 figure — men''s D2 is 5.4.'),
  ('Gymnastics', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Gymnastics', 'NAIA', null, null, null, 'Not found with confidence — gymnastics is rare at NAIA level, no reliable figure located.'),
  ('Gymnastics', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.'),
  ('Beach Volleyball', 'D1', 6, null, 6, 'Women''s sport. 2025-26 roster limit: 19.'),
  ('Beach Volleyball', 'D2', 5.0, null, 5.0, 'NCAA D2 equivalency limit.'),
  ('Beach Volleyball', 'D3', 0, null, null, 'NCAA D3 prohibits athletic scholarships.'),
  ('Beach Volleyball', 'NAIA', null, null, null, 'Not found with confidence — beach volleyball is rare at NAIA level, no reliable figure located.'),
  ('Beach Volleyball', 'JUCO', null, null, null, 'Tier-based (NJCAA D1 full/D2 partial/D3 none), no fixed per-sport count found.')
on conflict (sport, division) do update set
  total = excluded.total,
  head_count = excluded.head_count,
  equivalency = excluded.equivalency,
  notes = excluded.notes;
