-- Public player profile pages
-- Three tables:
--   player_profiles     — per-player profile config (slugs, visibility toggles, bio)
--   profile_tracking_links — one row per (profile, coach) for click tracking
--   profile_views       — detail log of every view event

CREATE TABLE IF NOT EXISTS player_profiles (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  family_unit_id  uuid NOT NULL REFERENCES family_units(id) ON DELETE CASCADE,
  hash_slug       text NOT NULL UNIQUE,
  vanity_slug     text UNIQUE,
  is_published    boolean NOT NULL DEFAULT false,
  bio             text,
  show_academics  boolean NOT NULL DEFAULT true,
  show_athletic   boolean NOT NULL DEFAULT true,
  show_film       boolean NOT NULL DEFAULT true,
  show_schools    boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  -- hash_slug: exactly 6 lowercase alphanumeric chars (generated by server)
  CONSTRAINT hash_slug_format  CHECK (hash_slug ~ '^[a-z0-9]{6}$'),
  -- vanity_slug: 2–30 chars, lowercase alphanumeric + hyphens, no leading/trailing hyphen
  CONSTRAINT vanity_slug_format CHECK (
    vanity_slug IS NULL
    OR vanity_slug ~ '^[a-z0-9][a-z0-9\-]{0,28}[a-z0-9]$'
  ),
  -- One profile per player (enforces idempotent auto-create in GET handler)
  UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS profile_tracking_links (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id      uuid NOT NULL REFERENCES player_profiles(id) ON DELETE CASCADE,
  coach_id        uuid NOT NULL REFERENCES coaches(id) ON DELETE CASCADE,
  ref_token       text NOT NULL UNIQUE,
  view_count      int NOT NULL DEFAULT 0,
  last_viewed_at  timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  -- One link per (profile, coach) — enforces idempotent "Send Profile"
  UNIQUE (profile_id, coach_id)
);

CREATE TABLE IF NOT EXISTS profile_views (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id          uuid NOT NULL REFERENCES player_profiles(id) ON DELETE CASCADE,
  tracking_link_id    uuid REFERENCES profile_tracking_links(id) ON DELETE SET NULL,
  viewed_at           timestamptz NOT NULL DEFAULT now(),
  user_agent          text
);

CREATE INDEX IF NOT EXISTS idx_profile_tracking_links_profile ON profile_tracking_links(profile_id);
CREATE INDEX IF NOT EXISTS idx_profile_views_profile          ON profile_views(profile_id);
CREATE INDEX IF NOT EXISTS idx_profile_views_tracking_link    ON profile_views(tracking_link_id);

-- Auto-update updated_at on any player_profiles row change
CREATE OR REPLACE FUNCTION set_player_profiles_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS player_profiles_updated_at ON player_profiles;
CREATE TRIGGER player_profiles_updated_at
  BEFORE UPDATE ON player_profiles
  FOR EACH ROW EXECUTE FUNCTION set_player_profiles_updated_at();

-- Atomic view count increment used by the view recording API
CREATE OR REPLACE FUNCTION increment_profile_link_view(link_id uuid)
RETURNS void LANGUAGE sql AS $$
  UPDATE profile_tracking_links
  SET view_count = view_count + 1, last_viewed_at = now()
  WHERE id = link_id;
$$;
